name: project2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  settings_ui: ^2.0.2
  table_calendar: ^3.0.0
  flutter_riverpod: ^1.0.0
  percent_indicator: ^4.0.0
  intl: ^0.17.0
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/profile.png
    - assets/google.png
    - assets/github.png
    - assets/twitter.png
    - assets/facebook.png