name: flutter_management_app
description: A Flutter application for managing projects, tasks, and more.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  table_calendar: ^3.0.9
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  image_picker: ^1.0.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/